---
networks:
  proxy:
    name: proxy
    driver: bridge
  db:
    name: db
    driver: bridge

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

services:
  traefik:
    image: traefik:v3.7.12
    container_name: traefik
    restart: unless-stopped
    logging: *default-logging
    command:
      - "--api.dashboard=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      # yamllint disable rule:line-length
      - "--certificatesresolvers.cloudflare.acme.email=${ACME_EMAIL:?ACME_EMAIL is required}"
      - "--certificatesresolvers.cloudflare.acme.storage=/acme.json"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1:53,1.0.0.1:53"
      # yamllint enable rule:line-length
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=proxy"
      - "--log.level=INFO"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/acme.json:/acme.json
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN:?CF_DNS_API_TOKEN is required}
    networks:
      - proxy

  mariadb:
    image: mariadb:12.2.2-noble
    container_name: mariadb
    restart: unless-stopped
    logging: *default-logging
    volumes:
      - ./mariadb/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:?required}
    networks:
      - db
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
